- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - default.yml
      paths:
        - 'vars'

- name: Copy files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    force: "{{ item.force | default('yes') }}"
  with_items:
  - {dest: ~/.zshrc.local, src: ~/.dotfiles/shell/zshrc.local, force: no}

- name: Create symbolic link 
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - { dest: "~/.bashrc", src: "{{ bashrc_path }}" }
    - { dest: "~/.zshrc", src: "{{ zshrc_path }}" }
