---
- name: Install packages
  hosts: localhost
  tags: 
    - packages
  roles:
  - packages

- name: Install configuration files
  hosts: localhost
  tags: 
    - configurations
  roles:
  - dotfiles
  - shell
  - vim
  - git

- name: Install mac settings
  hosts: localhost
  tags: 
    - mac
  roles:
  - mac-settings
