- name: Install packages
  homebrew:
    name: "{{ os_specific_packages }}"
    state: latest

- name: Install cask
  community.general.homebrew_cask:
    name:
    - aws-vault
    - keycastr
    state: present
