- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
      - '{{ ansible_distribution }}.yml'
      - '{{ ansible_os_family }}.yml'
      paths:
      - 'vars'

- name: Check if homebrew is installed
  shell: which brew >/dev/null 2>&1
  register: does_brew_exists
  ignore_errors: yes
  when: is_root_user

- name: Install homebrew
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  when: is_root_user and does_brew_exists.rc != 0 

- name: Install homebrew packages
  homebrew:
    name: "{{ common_packages }}"
    state: latest
  when: is_root_user

- name: Include ubuntu specific tasks
  include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu" and is_root_user

- name: Include MacOs specific tasks
  include: Darwin.yml
  when: ansible_os_family == "Darwin" and is_root_user

- name: Clone repos
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    force: true
    version: master
  with_items:
  - { dest: "~/.dotfiles/vim/vim-colors-solarized", repo: "https://github.com/altercation/vim-colors-solarized" }
  - { dest: "~/.dotfiles/packages/diff-so-fancy", repo: "https://github.com/so-fancy/diff-so-fancy" }
  - { dest: "~/.dotfiles/packages/powerline", repo: "https://github.com/powerline/fonts.git" }
  - { dest: "~/.fzf", repo: "https://github.com/junegunn/fzf.git" }
  - { dest: "~/.dotfiles/packages/iTerm2-Color-Schemes", repo: "https://github.com/mbadolato/iTerm2-Color-Schemes" }

- name: Post package commands
  shell: "{{ item }}"
  with_items:
    - ~/.fzf/install
    - ~/.dotfiles/packages/powerline/install.sh
    - 'rm -rf $HOME/.oh-my-zsh'
    - 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
    - 'curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh || true'

- name: Install python packages
  pip:
    name: PyYAML
