- name: Include ubuntu specific tasks
  include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  
- name: Include osx specific tasks
  include: Darwin.yml
  when: ansible_distribution == "Darwin"

- name: Clone repos
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    force: true
    version: master
  with_items:
  - { dest: "~/.dotfiles/vim/vim-colors-solarized", repo: "https://github.com/altercation/vim-colors-solarized" }
  - { dest: "~/.dotfiles/packages/diff-so-fancy", repo: "https://github.com/so-fancy/diff-so-fancy" }
