- name: Include ubuntu specific packages
  include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install packages
  homebrew:
    name:
    - bat
    - jq
    - tree
    - tmux
    - fzf
    - yamllint
    state: latest
