- name: Check if homebrew is installed
  shell: brew info >/dev/null 2>&1
  register: does_brew_exists
  ignore_errors: yes

- name: Install homebrew
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  when: does_brew_exists.rc != 0

- name: Set homebrew environment variables 
  blockinfile:
    create: yes
    dest: '~/.profile'
    mode: 0644
    state: present
    block: |
      eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
