# - name: Set homebrew environment variables 
#   blockinfile:
#     create: yes
#     dest: '~/.bashrc'
#     mode: 0644
#     state: present
#     block: |
#       eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
