- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: "{{ item.force | default('yes') }}"
  with_items:
    - { dest: "~/", src: "~/.dotfiles/dev", force: 'no' }

- name: Create symbolic link 
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { dest: "~/.gitconfig", src: "~/.dotfiles/git/gitconfig" }
