- name: Clone repos
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    force: true
    version: master
  with_items:
  - { dest: "~/.dotfiles/vim/vim-colors-solarized", repo: "https://github.com/altercation/vim-colors-solarized" }

- name: Copy files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    force: "{{ item.force | default('yes') }}"
  with_items:
  - {dest: ~/.vim/colors/, src: ~/.dotfiles/vim/vim-colors-solarized/colors/solarized.vim}
  - {dest: ~/.vimrc.local, src: ~/.dotfiles/vim/vimrc.local, force: no}

- name: Create symbolic link
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
  - {dest: ~/.vimrc, src: ~/.dotfiles/vim/vimrc}
